# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToutiaoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('url', models.CharField(default='', max_length=200)),
                ('source', models.CharField(default='', max_length=200)),
                ('commend', models.CharField(default='', max_length=20)),
                ('username', models.CharField(default='', max_length=200)),
                ('userurl', models.CharField(default='', max_length=200)),
                ('subjectname', models.CharField(default='', max_length=200)),
                ('subjecturl', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
