# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toutiaoio', '0003_auto_20160718_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='toutiaoitem',
            name='upvote',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
